// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

package com.gm.link.common.domain.protobuf;

public interface CompleteMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gm.link.common.domain.protobuf.CompleteMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return Whether the packetHeader field is set.
   */
  boolean hasPacketHeader();
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return The packetHeader.
   */
  com.gm.link.common.domain.protobuf.PacketHeader getPacketHeader();
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   */
  com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder getPacketHeaderOrBuilder();

  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return Whether the packetBody field is set.
   */
  boolean hasPacketBody();
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return The packetBody.
   */
  com.gm.link.common.domain.protobuf.PacketBody getPacketBody();
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   */
  com.gm.link.common.domain.protobuf.PacketBodyOrBuilder getPacketBodyOrBuilder();
}
