// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.gm.link.common.domain.protobuf.CompleteMessage}
 */
public final class CompleteMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gm.link.common.domain.protobuf.CompleteMessage)
    CompleteMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CompleteMessage.newBuilder() to construct.
  private CompleteMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CompleteMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CompleteMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CompleteMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.gm.link.common.domain.protobuf.PacketHeader.Builder subBuilder = null;
            if (packetHeader_ != null) {
              subBuilder = packetHeader_.toBuilder();
            }
            packetHeader_ = input.readMessage(com.gm.link.common.domain.protobuf.PacketHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(packetHeader_);
              packetHeader_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.gm.link.common.domain.protobuf.PacketBody.Builder subBuilder = null;
            if (packetBody_ != null) {
              subBuilder = packetBody_.toBuilder();
            }
            packetBody_ = input.readMessage(com.gm.link.common.domain.protobuf.PacketBody.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(packetBody_);
              packetBody_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_CompleteMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gm.link.common.domain.protobuf.CompleteMessage.class, com.gm.link.common.domain.protobuf.CompleteMessage.Builder.class);
  }

  public static final int PACKET_HEADER_FIELD_NUMBER = 1;
  private com.gm.link.common.domain.protobuf.PacketHeader packetHeader_;
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return Whether the packetHeader field is set.
   */
  @java.lang.Override
  public boolean hasPacketHeader() {
    return packetHeader_ != null;
  }
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   * @return The packetHeader.
   */
  @java.lang.Override
  public com.gm.link.common.domain.protobuf.PacketHeader getPacketHeader() {
    return packetHeader_ == null ? com.gm.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
  }
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
   */
  @java.lang.Override
  public com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder getPacketHeaderOrBuilder() {
    return getPacketHeader();
  }

  public static final int PACKET_BODY_FIELD_NUMBER = 2;
  private com.gm.link.common.domain.protobuf.PacketBody packetBody_;
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return Whether the packetBody field is set.
   */
  @java.lang.Override
  public boolean hasPacketBody() {
    return packetBody_ != null;
  }
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   * @return The packetBody.
   */
  @java.lang.Override
  public com.gm.link.common.domain.protobuf.PacketBody getPacketBody() {
    return packetBody_ == null ? com.gm.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
  }
  /**
   * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
   */
  @java.lang.Override
  public com.gm.link.common.domain.protobuf.PacketBodyOrBuilder getPacketBodyOrBuilder() {
    return getPacketBody();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (packetHeader_ != null) {
      output.writeMessage(1, getPacketHeader());
    }
    if (packetBody_ != null) {
      output.writeMessage(2, getPacketBody());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (packetHeader_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPacketHeader());
    }
    if (packetBody_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPacketBody());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gm.link.common.domain.protobuf.CompleteMessage)) {
      return super.equals(obj);
    }
    com.gm.link.common.domain.protobuf.CompleteMessage other = (com.gm.link.common.domain.protobuf.CompleteMessage) obj;

    if (hasPacketHeader() != other.hasPacketHeader()) return false;
    if (hasPacketHeader()) {
      if (!getPacketHeader()
          .equals(other.getPacketHeader())) return false;
    }
    if (hasPacketBody() != other.hasPacketBody()) return false;
    if (hasPacketBody()) {
      if (!getPacketBody()
          .equals(other.getPacketBody())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPacketHeader()) {
      hash = (37 * hash) + PACKET_HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getPacketHeader().hashCode();
    }
    if (hasPacketBody()) {
      hash = (37 * hash) + PACKET_BODY_FIELD_NUMBER;
      hash = (53 * hash) + getPacketBody().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.CompleteMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gm.link.common.domain.protobuf.CompleteMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gm.link.common.domain.protobuf.CompleteMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gm.link.common.domain.protobuf.CompleteMessage)
      com.gm.link.common.domain.protobuf.CompleteMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_CompleteMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_CompleteMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.link.common.domain.protobuf.CompleteMessage.class, com.gm.link.common.domain.protobuf.CompleteMessage.Builder.class);
    }

    // Construct using com.gm.link.common.domain.protobuf.CompleteMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (packetHeaderBuilder_ == null) {
        packetHeader_ = null;
      } else {
        packetHeader_ = null;
        packetHeaderBuilder_ = null;
      }
      if (packetBodyBuilder_ == null) {
        packetBody_ = null;
      } else {
        packetBody_ = null;
        packetBodyBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_CompleteMessage_descriptor;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.CompleteMessage getDefaultInstanceForType() {
      return com.gm.link.common.domain.protobuf.CompleteMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.CompleteMessage build() {
      com.gm.link.common.domain.protobuf.CompleteMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.CompleteMessage buildPartial() {
      com.gm.link.common.domain.protobuf.CompleteMessage result = new com.gm.link.common.domain.protobuf.CompleteMessage(this);
      if (packetHeaderBuilder_ == null) {
        result.packetHeader_ = packetHeader_;
      } else {
        result.packetHeader_ = packetHeaderBuilder_.build();
      }
      if (packetBodyBuilder_ == null) {
        result.packetBody_ = packetBody_;
      } else {
        result.packetBody_ = packetBodyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gm.link.common.domain.protobuf.CompleteMessage) {
        return mergeFrom((com.gm.link.common.domain.protobuf.CompleteMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gm.link.common.domain.protobuf.CompleteMessage other) {
      if (other == com.gm.link.common.domain.protobuf.CompleteMessage.getDefaultInstance()) return this;
      if (other.hasPacketHeader()) {
        mergePacketHeader(other.getPacketHeader());
      }
      if (other.hasPacketBody()) {
        mergePacketBody(other.getPacketBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gm.link.common.domain.protobuf.CompleteMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gm.link.common.domain.protobuf.CompleteMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.gm.link.common.domain.protobuf.PacketHeader packetHeader_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gm.link.common.domain.protobuf.PacketHeader, com.gm.link.common.domain.protobuf.PacketHeader.Builder, com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder> packetHeaderBuilder_;
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     * @return Whether the packetHeader field is set.
     */
    public boolean hasPacketHeader() {
      return packetHeaderBuilder_ != null || packetHeader_ != null;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     * @return The packetHeader.
     */
    public com.gm.link.common.domain.protobuf.PacketHeader getPacketHeader() {
      if (packetHeaderBuilder_ == null) {
        return packetHeader_ == null ? com.gm.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
      } else {
        return packetHeaderBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder setPacketHeader(com.gm.link.common.domain.protobuf.PacketHeader value) {
      if (packetHeaderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetHeader_ = value;
        onChanged();
      } else {
        packetHeaderBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder setPacketHeader(
        com.gm.link.common.domain.protobuf.PacketHeader.Builder builderForValue) {
      if (packetHeaderBuilder_ == null) {
        packetHeader_ = builderForValue.build();
        onChanged();
      } else {
        packetHeaderBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder mergePacketHeader(com.gm.link.common.domain.protobuf.PacketHeader value) {
      if (packetHeaderBuilder_ == null) {
        if (packetHeader_ != null) {
          packetHeader_ =
            com.gm.link.common.domain.protobuf.PacketHeader.newBuilder(packetHeader_).mergeFrom(value).buildPartial();
        } else {
          packetHeader_ = value;
        }
        onChanged();
      } else {
        packetHeaderBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public Builder clearPacketHeader() {
      if (packetHeaderBuilder_ == null) {
        packetHeader_ = null;
        onChanged();
      } else {
        packetHeader_ = null;
        packetHeaderBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public com.gm.link.common.domain.protobuf.PacketHeader.Builder getPacketHeaderBuilder() {
      
      onChanged();
      return getPacketHeaderFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    public com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder getPacketHeaderOrBuilder() {
      if (packetHeaderBuilder_ != null) {
        return packetHeaderBuilder_.getMessageOrBuilder();
      } else {
        return packetHeader_ == null ?
            com.gm.link.common.domain.protobuf.PacketHeader.getDefaultInstance() : packetHeader_;
      }
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketHeader packet_header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gm.link.common.domain.protobuf.PacketHeader, com.gm.link.common.domain.protobuf.PacketHeader.Builder, com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder> 
        getPacketHeaderFieldBuilder() {
      if (packetHeaderBuilder_ == null) {
        packetHeaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gm.link.common.domain.protobuf.PacketHeader, com.gm.link.common.domain.protobuf.PacketHeader.Builder, com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder>(
                getPacketHeader(),
                getParentForChildren(),
                isClean());
        packetHeader_ = null;
      }
      return packetHeaderBuilder_;
    }

    private com.gm.link.common.domain.protobuf.PacketBody packetBody_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gm.link.common.domain.protobuf.PacketBody, com.gm.link.common.domain.protobuf.PacketBody.Builder, com.gm.link.common.domain.protobuf.PacketBodyOrBuilder> packetBodyBuilder_;
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     * @return Whether the packetBody field is set.
     */
    public boolean hasPacketBody() {
      return packetBodyBuilder_ != null || packetBody_ != null;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     * @return The packetBody.
     */
    public com.gm.link.common.domain.protobuf.PacketBody getPacketBody() {
      if (packetBodyBuilder_ == null) {
        return packetBody_ == null ? com.gm.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
      } else {
        return packetBodyBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder setPacketBody(com.gm.link.common.domain.protobuf.PacketBody value) {
      if (packetBodyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        packetBody_ = value;
        onChanged();
      } else {
        packetBodyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder setPacketBody(
        com.gm.link.common.domain.protobuf.PacketBody.Builder builderForValue) {
      if (packetBodyBuilder_ == null) {
        packetBody_ = builderForValue.build();
        onChanged();
      } else {
        packetBodyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder mergePacketBody(com.gm.link.common.domain.protobuf.PacketBody value) {
      if (packetBodyBuilder_ == null) {
        if (packetBody_ != null) {
          packetBody_ =
            com.gm.link.common.domain.protobuf.PacketBody.newBuilder(packetBody_).mergeFrom(value).buildPartial();
        } else {
          packetBody_ = value;
        }
        onChanged();
      } else {
        packetBodyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public Builder clearPacketBody() {
      if (packetBodyBuilder_ == null) {
        packetBody_ = null;
        onChanged();
      } else {
        packetBody_ = null;
        packetBodyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public com.gm.link.common.domain.protobuf.PacketBody.Builder getPacketBodyBuilder() {
      
      onChanged();
      return getPacketBodyFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    public com.gm.link.common.domain.protobuf.PacketBodyOrBuilder getPacketBodyOrBuilder() {
      if (packetBodyBuilder_ != null) {
        return packetBodyBuilder_.getMessageOrBuilder();
      } else {
        return packetBody_ == null ?
            com.gm.link.common.domain.protobuf.PacketBody.getDefaultInstance() : packetBody_;
      }
    }
    /**
     * <code>.com.gm.link.common.domain.protobuf.PacketBody packet_body = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.gm.link.common.domain.protobuf.PacketBody, com.gm.link.common.domain.protobuf.PacketBody.Builder, com.gm.link.common.domain.protobuf.PacketBodyOrBuilder> 
        getPacketBodyFieldBuilder() {
      if (packetBodyBuilder_ == null) {
        packetBodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.gm.link.common.domain.protobuf.PacketBody, com.gm.link.common.domain.protobuf.PacketBody.Builder, com.gm.link.common.domain.protobuf.PacketBodyOrBuilder>(
                getPacketBody(),
                getParentForChildren(),
                isClean());
        packetBody_ = null;
      }
      return packetBodyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gm.link.common.domain.protobuf.CompleteMessage)
  }

  // @@protoc_insertion_point(class_scope:com.gm.link.common.domain.protobuf.CompleteMessage)
  private static final com.gm.link.common.domain.protobuf.CompleteMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gm.link.common.domain.protobuf.CompleteMessage();
  }

  public static com.gm.link.common.domain.protobuf.CompleteMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CompleteMessage>
      PARSER = new com.google.protobuf.AbstractParser<CompleteMessage>() {
    @java.lang.Override
    public CompleteMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CompleteMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CompleteMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CompleteMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gm.link.common.domain.protobuf.CompleteMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

