// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

package com.gm.link.common.domain.protobuf;

public final class LinkMessage {
  private LinkMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gm_link_common_domain_protobuf_PacketHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_link_common_domain_protobuf_PacketBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gm_link_common_domain_protobuf_PacketBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022link_message.proto\022\"com.gm.link.common" +
      ".domain.protobuf\"x\n\014PacketHeader\022\016\n\006app_" +
      "id\030\001 \001(\007\022\013\n\003uid\030\002 \001(\006\022\r\n\005token\030\003 \001(\t\022\023\n\013" +
      "compression\030\004 \001(\005\022\022\n\nencryption\030\005 \001(\005\022\023\n" +
      "\013messageType\030\006 \001(\005\"\032\n\nPacketBody\022\014\n\004data" +
      "\030\001 \001(\tB&\n\"com.gm.link.common.domain.prot" +
      "obufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gm_link_common_domain_protobuf_PacketHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor,
        new java.lang.String[] { "AppId", "Uid", "Token", "Compression", "Encryption", "MessageType", });
    internal_static_com_gm_link_common_domain_protobuf_PacketBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gm_link_common_domain_protobuf_PacketBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gm_link_common_domain_protobuf_PacketBody_descriptor,
        new java.lang.String[] { "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
