// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf enum {@code com.gm.link.common.domain.protobuf.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MSG_UNKNOWN = 0;</code>
   */
  MSG_UNKNOWN(0),
  /**
   * <pre>
   * 文本消息
   * </pre>
   *
   * <code>MSG_TEXT = 1;</code>
   */
  MSG_TEXT(1),
  /**
   * <pre>
   * 图片消息
   * </pre>
   *
   * <code>MSG_IMAGE = 2;</code>
   */
  MSG_IMAGE(2),
  /**
   * <pre>
   * 语音消息
   * </pre>
   *
   * <code>MSG_VOICE = 3;</code>
   */
  MSG_VOICE(3),
  /**
   * <pre>
   * 视频消息
   * </pre>
   *
   * <code>MSG_VIDEO = 4;</code>
   */
  MSG_VIDEO(4),
  /**
   * <pre>
   * 文件消息
   * </pre>
   *
   * <code>MSG_FILE = 5;</code>
   */
  MSG_FILE(5),
  /**
   * <pre>
   * 控制命令
   * </pre>
   *
   * <code>MSG_CMD = 6;</code>
   */
  MSG_CMD(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MSG_UNKNOWN = 0;</code>
   */
  public static final int MSG_UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 文本消息
   * </pre>
   *
   * <code>MSG_TEXT = 1;</code>
   */
  public static final int MSG_TEXT_VALUE = 1;
  /**
   * <pre>
   * 图片消息
   * </pre>
   *
   * <code>MSG_IMAGE = 2;</code>
   */
  public static final int MSG_IMAGE_VALUE = 2;
  /**
   * <pre>
   * 语音消息
   * </pre>
   *
   * <code>MSG_VOICE = 3;</code>
   */
  public static final int MSG_VOICE_VALUE = 3;
  /**
   * <pre>
   * 视频消息
   * </pre>
   *
   * <code>MSG_VIDEO = 4;</code>
   */
  public static final int MSG_VIDEO_VALUE = 4;
  /**
   * <pre>
   * 文件消息
   * </pre>
   *
   * <code>MSG_FILE = 5;</code>
   */
  public static final int MSG_FILE_VALUE = 5;
  /**
   * <pre>
   * 控制命令
   * </pre>
   *
   * <code>MSG_CMD = 6;</code>
   */
  public static final int MSG_CMD_VALUE = 6;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return MSG_UNKNOWN;
      case 1: return MSG_TEXT;
      case 2: return MSG_IMAGE;
      case 3: return MSG_VOICE;
      case 4: return MSG_VIDEO;
      case 5: return MSG_FILE;
      case 6: return MSG_CMD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.ProtoMessageOuter.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gm.link.common.domain.protobuf.MessageType)
}

