// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf enum {@code com.gm.link.common.domain.protobuf.MessageStatus}
 */
public enum MessageStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 发送中
   * </pre>
   *
   * <code>STATUS_SENDING = 0;</code>
   */
  STATUS_SENDING(0),
  /**
   * <pre>
   * 已发送
   * </pre>
   *
   * <code>STATUS_SENT = 1;</code>
   */
  STATUS_SENT(1),
  /**
   * <pre>
   * 已送达
   * </pre>
   *
   * <code>STATUS_DELIVERED = 2;</code>
   */
  STATUS_DELIVERED(2),
  /**
   * <pre>
   * 已读
   * </pre>
   *
   * <code>STATUS_READ = 3;</code>
   */
  STATUS_READ(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 发送中
   * </pre>
   *
   * <code>STATUS_SENDING = 0;</code>
   */
  public static final int STATUS_SENDING_VALUE = 0;
  /**
   * <pre>
   * 已发送
   * </pre>
   *
   * <code>STATUS_SENT = 1;</code>
   */
  public static final int STATUS_SENT_VALUE = 1;
  /**
   * <pre>
   * 已送达
   * </pre>
   *
   * <code>STATUS_DELIVERED = 2;</code>
   */
  public static final int STATUS_DELIVERED_VALUE = 2;
  /**
   * <pre>
   * 已读
   * </pre>
   *
   * <code>STATUS_READ = 3;</code>
   */
  public static final int STATUS_READ_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageStatus forNumber(int value) {
    switch (value) {
      case 0: return STATUS_SENDING;
      case 1: return STATUS_SENT;
      case 2: return STATUS_DELIVERED;
      case 3: return STATUS_READ;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageStatus>() {
          public MessageStatus findValueByNumber(int number) {
            return MessageStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.ProtoMessageOuter.getDescriptor().getEnumTypes().get(1);
  }

  private static final MessageStatus[] VALUES = values();

  public static MessageStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.gm.link.common.domain.protobuf.MessageStatus)
}

