// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

package com.gm.link.common.domain.protobuf;

public interface PacketBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gm.link.common.domain.protobuf.PacketBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 from_user_id = 1;</code>
   * @return The fromUserId.
   */
  long getFromUserId();

  /**
   * <code>int64 time_stamp = 2;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <code>int64 to_id = 3;</code>
   * @return The toId.
   */
  long getToId();

  /**
   * <code>int32 message_type = 4;</code>
   * @return The messageType.
   */
  int getMessageType();

  /**
   * <code>string content = 5;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
