// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: link_message.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.gm.link.common.domain.protobuf.PacketHeader}
 */
public final class PacketHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gm.link.common.domain.protobuf.PacketHeader)
    PacketHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PacketHeader.newBuilder() to construct.
  private PacketHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PacketHeader() {
    token_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PacketHeader();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PacketHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            appId_ = input.readFixed32();
            break;
          }
          case 17: {

            uid_ = input.readFixed64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 32: {

            compression_ = input.readInt32();
            break;
          }
          case 40: {

            encryption_ = input.readInt32();
            break;
          }
          case 48: {

            messageType_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_PacketHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gm.link.common.domain.protobuf.PacketHeader.class, com.gm.link.common.domain.protobuf.PacketHeader.Builder.class);
  }

  public static final int APP_ID_FIELD_NUMBER = 1;
  private int appId_;
  /**
   * <pre>
   * 业务id，Link也是一个业务，标识所属业务模块
   * </pre>
   *
   * <code>fixed32 app_id = 1;</code>
   * @return The appId.
   */
  @java.lang.Override
  public int getAppId() {
    return appId_;
  }

  public static final int UID_FIELD_NUMBER = 2;
  private long uid_;
  /**
   * <pre>
   * 用户id，标识发送方
   * </pre>
   *
   * <code>fixed64 uid = 2;</code>
   * @return The uid.
   */
  @java.lang.Override
  public long getUid() {
    return uid_;
  }

  public static final int TOKEN_FIELD_NUMBER = 3;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   * 用户凭证，验证用户身份，16字节，可根据业务调整
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The token.
   */
  @java.lang.Override
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 用户凭证，验证用户身份，16字节，可根据业务调整
   * </pre>
   *
   * <code>string token = 3;</code>
   * @return The bytes for token.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPRESSION_FIELD_NUMBER = 4;
  private int compression_;
  /**
   * <pre>
   * 1字节，压缩方式，标识是否启用压缩，0-不压缩，1-gzip
   * </pre>
   *
   * <code>int32 compression = 4;</code>
   * @return The compression.
   */
  @java.lang.Override
  public int getCompression() {
    return compression_;
  }

  public static final int ENCRYPTION_FIELD_NUMBER = 5;
  private int encryption_;
  /**
   * <pre>
   * 1字节，加密方式，标识是否启用加密，0-不加密，1-aes
   * </pre>
   *
   * <code>int32 encryption = 5;</code>
   * @return The encryption.
   */
  @java.lang.Override
  public int getEncryption() {
    return encryption_;
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 6;
  private int messageType_;
  /**
   * <pre>
   * 2字节，数据类型标识，标识数据类型，0-客户端登录，1-心跳，2-ack，3-强制下线,4-私聊，
   * </pre>
   *
   * <code>int32 messageType = 6;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public int getMessageType() {
    return messageType_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (appId_ != 0) {
      output.writeFixed32(1, appId_);
    }
    if (uid_ != 0L) {
      output.writeFixed64(2, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, token_);
    }
    if (compression_ != 0) {
      output.writeInt32(4, compression_);
    }
    if (encryption_ != 0) {
      output.writeInt32(5, encryption_);
    }
    if (messageType_ != 0) {
      output.writeInt32(6, messageType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (appId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, appId_);
    }
    if (uid_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(2, uid_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(token_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, token_);
    }
    if (compression_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, compression_);
    }
    if (encryption_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, encryption_);
    }
    if (messageType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, messageType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gm.link.common.domain.protobuf.PacketHeader)) {
      return super.equals(obj);
    }
    com.gm.link.common.domain.protobuf.PacketHeader other = (com.gm.link.common.domain.protobuf.PacketHeader) obj;

    if (getAppId()
        != other.getAppId()) return false;
    if (getUid()
        != other.getUid()) return false;
    if (!getToken()
        .equals(other.getToken())) return false;
    if (getCompression()
        != other.getCompression()) return false;
    if (getEncryption()
        != other.getEncryption()) return false;
    if (getMessageType()
        != other.getMessageType()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + APP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAppId();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUid());
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + COMPRESSION_FIELD_NUMBER;
    hash = (53 * hash) + getCompression();
    hash = (37 * hash) + ENCRYPTION_FIELD_NUMBER;
    hash = (53 * hash) + getEncryption();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.PacketHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gm.link.common.domain.protobuf.PacketHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gm.link.common.domain.protobuf.PacketHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gm.link.common.domain.protobuf.PacketHeader)
      com.gm.link.common.domain.protobuf.PacketHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_PacketHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.link.common.domain.protobuf.PacketHeader.class, com.gm.link.common.domain.protobuf.PacketHeader.Builder.class);
    }

    // Construct using com.gm.link.common.domain.protobuf.PacketHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      appId_ = 0;

      uid_ = 0L;

      token_ = "";

      compression_ = 0;

      encryption_ = 0;

      messageType_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gm.link.common.domain.protobuf.LinkMessage.internal_static_com_gm_link_common_domain_protobuf_PacketHeader_descriptor;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.PacketHeader getDefaultInstanceForType() {
      return com.gm.link.common.domain.protobuf.PacketHeader.getDefaultInstance();
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.PacketHeader build() {
      com.gm.link.common.domain.protobuf.PacketHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.PacketHeader buildPartial() {
      com.gm.link.common.domain.protobuf.PacketHeader result = new com.gm.link.common.domain.protobuf.PacketHeader(this);
      result.appId_ = appId_;
      result.uid_ = uid_;
      result.token_ = token_;
      result.compression_ = compression_;
      result.encryption_ = encryption_;
      result.messageType_ = messageType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gm.link.common.domain.protobuf.PacketHeader) {
        return mergeFrom((com.gm.link.common.domain.protobuf.PacketHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gm.link.common.domain.protobuf.PacketHeader other) {
      if (other == com.gm.link.common.domain.protobuf.PacketHeader.getDefaultInstance()) return this;
      if (other.getAppId() != 0) {
        setAppId(other.getAppId());
      }
      if (other.getUid() != 0L) {
        setUid(other.getUid());
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (other.getCompression() != 0) {
        setCompression(other.getCompression());
      }
      if (other.getEncryption() != 0) {
        setEncryption(other.getEncryption());
      }
      if (other.getMessageType() != 0) {
        setMessageType(other.getMessageType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gm.link.common.domain.protobuf.PacketHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gm.link.common.domain.protobuf.PacketHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int appId_ ;
    /**
     * <pre>
     * 业务id，Link也是一个业务，标识所属业务模块
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @return The appId.
     */
    @java.lang.Override
    public int getAppId() {
      return appId_;
    }
    /**
     * <pre>
     * 业务id，Link也是一个业务，标识所属业务模块
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(int value) {
      
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务id，Link也是一个业务，标识所属业务模块
     * </pre>
     *
     * <code>fixed32 app_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      
      appId_ = 0;
      onChanged();
      return this;
    }

    private long uid_ ;
    /**
     * <pre>
     * 用户id，标识发送方
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @return The uid.
     */
    @java.lang.Override
    public long getUid() {
      return uid_;
    }
    /**
     * <pre>
     * 用户id，标识发送方
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(long value) {
      
      uid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户id，标识发送方
     * </pre>
     *
     * <code>fixed64 uid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      
      uid_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     * 用户凭证，验证用户身份，16字节，可根据业务调整
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return The token.
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 用户凭证，验证用户身份，16字节，可根据业务调整
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return The bytes for token.
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 用户凭证，验证用户身份，16字节，可根据业务调整
     * </pre>
     *
     * <code>string token = 3;</code>
     * @param value The token to set.
     * @return This builder for chaining.
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户凭证，验证用户身份，16字节，可根据业务调整
     * </pre>
     *
     * <code>string token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户凭证，验证用户身份，16字节，可根据业务调整
     * </pre>
     *
     * <code>string token = 3;</code>
     * @param value The bytes for token to set.
     * @return This builder for chaining.
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private int compression_ ;
    /**
     * <pre>
     * 1字节，压缩方式，标识是否启用压缩，0-不压缩，1-gzip
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @return The compression.
     */
    @java.lang.Override
    public int getCompression() {
      return compression_;
    }
    /**
     * <pre>
     * 1字节，压缩方式，标识是否启用压缩，0-不压缩，1-gzip
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @param value The compression to set.
     * @return This builder for chaining.
     */
    public Builder setCompression(int value) {
      
      compression_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1字节，压缩方式，标识是否启用压缩，0-不压缩，1-gzip
     * </pre>
     *
     * <code>int32 compression = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompression() {
      
      compression_ = 0;
      onChanged();
      return this;
    }

    private int encryption_ ;
    /**
     * <pre>
     * 1字节，加密方式，标识是否启用加密，0-不加密，1-aes
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @return The encryption.
     */
    @java.lang.Override
    public int getEncryption() {
      return encryption_;
    }
    /**
     * <pre>
     * 1字节，加密方式，标识是否启用加密，0-不加密，1-aes
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @param value The encryption to set.
     * @return This builder for chaining.
     */
    public Builder setEncryption(int value) {
      
      encryption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 1字节，加密方式，标识是否启用加密，0-不加密，1-aes
     * </pre>
     *
     * <code>int32 encryption = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryption() {
      
      encryption_ = 0;
      onChanged();
      return this;
    }

    private int messageType_ ;
    /**
     * <pre>
     * 2字节，数据类型标识，标识数据类型，0-客户端登录，1-心跳，2-ack，3-强制下线,4-私聊，
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public int getMessageType() {
      return messageType_;
    }
    /**
     * <pre>
     * 2字节，数据类型标识，标识数据类型，0-客户端登录，1-心跳，2-ack，3-强制下线,4-私聊，
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节，数据类型标识，标识数据类型，0-客户端登录，1-心跳，2-ack，3-强制下线,4-私聊，
     * </pre>
     *
     * <code>int32 messageType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gm.link.common.domain.protobuf.PacketHeader)
  }

  // @@protoc_insertion_point(class_scope:com.gm.link.common.domain.protobuf.PacketHeader)
  private static final com.gm.link.common.domain.protobuf.PacketHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gm.link.common.domain.protobuf.PacketHeader();
  }

  public static com.gm.link.common.domain.protobuf.PacketHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PacketHeader>
      PARSER = new com.google.protobuf.AbstractParser<PacketHeader>() {
    @java.lang.Override
    public PacketHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PacketHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PacketHeader> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PacketHeader> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gm.link.common.domain.protobuf.PacketHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

