// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoHB.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoHB}
 */
public final class ProtoHB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gm.link.common.domain.protobuf.ProtoHB)
    ProtoHBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoHB.newBuilder() to construct.
  private ProtoHB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoHB() {
    fromMachineId_ = "";
    toMachineId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoHB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoHB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            magic_ = input.readFixed32();
            break;
          }
          case 16: {

            version_ = input.readInt32();
            break;
          }
          case 24: {

            cmd_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fromMachineId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            toMachineId_ = s;
            break;
          }
          case 48: {

            timestamp_ = input.readInt64();
            break;
          }
          case 61: {

            checkSum_ = input.readFixed32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.ProtoHBOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoHB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gm.link.common.domain.protobuf.ProtoHBOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoHB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gm.link.common.domain.protobuf.ProtoHB.class, com.gm.link.common.domain.protobuf.ProtoHB.Builder.class);
  }

  public static final int MAGIC_FIELD_NUMBER = 1;
  private int magic_;
  /**
   * <pre>
   * 固定4字节魔数(0xDEADBEEF)
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  @java.lang.Override
  public int getMagic() {
    return magic_;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_;
  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>int32 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int CMD_FIELD_NUMBER = 3;
  private int cmd_;
  /**
   * <pre>
   * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
   * </pre>
   *
   * <code>int32 cmd = 3;</code>
   * @return The cmd.
   */
  @java.lang.Override
  public int getCmd() {
    return cmd_;
  }

  public static final int FROM_MACHINE_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object fromMachineId_;
  /**
   * <pre>
   * 发送端机器标识
   * </pre>
   *
   * <code>string from_machine_id = 4;</code>
   * @return The fromMachineId.
   */
  @java.lang.Override
  public java.lang.String getFromMachineId() {
    java.lang.Object ref = fromMachineId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromMachineId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送端机器标识
   * </pre>
   *
   * <code>string from_machine_id = 4;</code>
   * @return The bytes for fromMachineId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromMachineIdBytes() {
    java.lang.Object ref = fromMachineId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromMachineId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_MACHINE_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object toMachineId_;
  /**
   * <pre>
   * 接收端机器标识
   * </pre>
   *
   * <code>string to_machine_id = 5;</code>
   * @return The toMachineId.
   */
  @java.lang.Override
  public java.lang.String getToMachineId() {
    java.lang.Object ref = toMachineId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toMachineId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 接收端机器标识
   * </pre>
   *
   * <code>string to_machine_id = 5;</code>
   * @return The bytes for toMachineId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToMachineIdBytes() {
    java.lang.Object ref = toMachineId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toMachineId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <pre>
   * 心跳扩展信息
   * </pre>
   *
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int CHECK_SUM_FIELD_NUMBER = 7;
  private int checkSum_;
  /**
   * <pre>
   * 校验码(时间戳+机器ID)
   * </pre>
   *
   * <code>fixed32 check_sum = 7;</code>
   * @return The checkSum.
   */
  @java.lang.Override
  public int getCheckSum() {
    return checkSum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (magic_ != 0) {
      output.writeFixed32(1, magic_);
    }
    if (version_ != 0) {
      output.writeInt32(2, version_);
    }
    if (cmd_ != 0) {
      output.writeInt32(3, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromMachineId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromMachineId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toMachineId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, toMachineId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (checkSum_ != 0) {
      output.writeFixed32(7, checkSum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (magic_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, magic_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, version_);
    }
    if (cmd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromMachineId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromMachineId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(toMachineId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, toMachineId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (checkSum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(7, checkSum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gm.link.common.domain.protobuf.ProtoHB)) {
      return super.equals(obj);
    }
    com.gm.link.common.domain.protobuf.ProtoHB other = (com.gm.link.common.domain.protobuf.ProtoHB) obj;

    if (getMagic()
        != other.getMagic()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getCmd()
        != other.getCmd()) return false;
    if (!getFromMachineId()
        .equals(other.getFromMachineId())) return false;
    if (!getToMachineId()
        .equals(other.getToMachineId())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getCheckSum()
        != other.getCheckSum()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAGIC_FIELD_NUMBER;
    hash = (53 * hash) + getMagic();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd();
    hash = (37 * hash) + FROM_MACHINE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFromMachineId().hashCode();
    hash = (37 * hash) + TO_MACHINE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getToMachineId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + CHECK_SUM_FIELD_NUMBER;
    hash = (53 * hash) + getCheckSum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoHB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gm.link.common.domain.protobuf.ProtoHB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoHB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gm.link.common.domain.protobuf.ProtoHB)
      com.gm.link.common.domain.protobuf.ProtoHBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.link.common.domain.protobuf.ProtoHBOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoHB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.link.common.domain.protobuf.ProtoHBOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoHB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.link.common.domain.protobuf.ProtoHB.class, com.gm.link.common.domain.protobuf.ProtoHB.Builder.class);
    }

    // Construct using com.gm.link.common.domain.protobuf.ProtoHB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      magic_ = 0;

      version_ = 0;

      cmd_ = 0;

      fromMachineId_ = "";

      toMachineId_ = "";

      timestamp_ = 0L;

      checkSum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gm.link.common.domain.protobuf.ProtoHBOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoHB_descriptor;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoHB getDefaultInstanceForType() {
      return com.gm.link.common.domain.protobuf.ProtoHB.getDefaultInstance();
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoHB build() {
      com.gm.link.common.domain.protobuf.ProtoHB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoHB buildPartial() {
      com.gm.link.common.domain.protobuf.ProtoHB result = new com.gm.link.common.domain.protobuf.ProtoHB(this);
      result.magic_ = magic_;
      result.version_ = version_;
      result.cmd_ = cmd_;
      result.fromMachineId_ = fromMachineId_;
      result.toMachineId_ = toMachineId_;
      result.timestamp_ = timestamp_;
      result.checkSum_ = checkSum_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gm.link.common.domain.protobuf.ProtoHB) {
        return mergeFrom((com.gm.link.common.domain.protobuf.ProtoHB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gm.link.common.domain.protobuf.ProtoHB other) {
      if (other == com.gm.link.common.domain.protobuf.ProtoHB.getDefaultInstance()) return this;
      if (other.getMagic() != 0) {
        setMagic(other.getMagic());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCmd() != 0) {
        setCmd(other.getCmd());
      }
      if (!other.getFromMachineId().isEmpty()) {
        fromMachineId_ = other.fromMachineId_;
        onChanged();
      }
      if (!other.getToMachineId().isEmpty()) {
        toMachineId_ = other.toMachineId_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getCheckSum() != 0) {
        setCheckSum(other.getCheckSum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gm.link.common.domain.protobuf.ProtoHB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gm.link.common.domain.protobuf.ProtoHB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int magic_ ;
    /**
     * <pre>
     * 固定4字节魔数(0xDEADBEEF)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return The magic.
     */
    @java.lang.Override
    public int getMagic() {
      return magic_;
    }
    /**
     * <pre>
     * 固定4字节魔数(0xDEADBEEF)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @param value The magic to set.
     * @return This builder for chaining.
     */
    public Builder setMagic(int value) {
      
      magic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 固定4字节魔数(0xDEADBEEF)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMagic() {
      
      magic_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>int32 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>int32 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private int cmd_ ;
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>int32 cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
      return cmd_;
    }
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>int32 cmd = 3;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(int value) {
      
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>int32 cmd = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object fromMachineId_ = "";
    /**
     * <pre>
     * 发送端机器标识
     * </pre>
     *
     * <code>string from_machine_id = 4;</code>
     * @return The fromMachineId.
     */
    public java.lang.String getFromMachineId() {
      java.lang.Object ref = fromMachineId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromMachineId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送端机器标识
     * </pre>
     *
     * <code>string from_machine_id = 4;</code>
     * @return The bytes for fromMachineId.
     */
    public com.google.protobuf.ByteString
        getFromMachineIdBytes() {
      java.lang.Object ref = fromMachineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromMachineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送端机器标识
     * </pre>
     *
     * <code>string from_machine_id = 4;</code>
     * @param value The fromMachineId to set.
     * @return This builder for chaining.
     */
    public Builder setFromMachineId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromMachineId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送端机器标识
     * </pre>
     *
     * <code>string from_machine_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromMachineId() {
      
      fromMachineId_ = getDefaultInstance().getFromMachineId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送端机器标识
     * </pre>
     *
     * <code>string from_machine_id = 4;</code>
     * @param value The bytes for fromMachineId to set.
     * @return This builder for chaining.
     */
    public Builder setFromMachineIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromMachineId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toMachineId_ = "";
    /**
     * <pre>
     * 接收端机器标识
     * </pre>
     *
     * <code>string to_machine_id = 5;</code>
     * @return The toMachineId.
     */
    public java.lang.String getToMachineId() {
      java.lang.Object ref = toMachineId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toMachineId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 接收端机器标识
     * </pre>
     *
     * <code>string to_machine_id = 5;</code>
     * @return The bytes for toMachineId.
     */
    public com.google.protobuf.ByteString
        getToMachineIdBytes() {
      java.lang.Object ref = toMachineId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toMachineId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 接收端机器标识
     * </pre>
     *
     * <code>string to_machine_id = 5;</code>
     * @param value The toMachineId to set.
     * @return This builder for chaining.
     */
    public Builder setToMachineId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      toMachineId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收端机器标识
     * </pre>
     *
     * <code>string to_machine_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearToMachineId() {
      
      toMachineId_ = getDefaultInstance().getToMachineId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 接收端机器标识
     * </pre>
     *
     * <code>string to_machine_id = 5;</code>
     * @param value The bytes for toMachineId to set.
     * @return This builder for chaining.
     */
    public Builder setToMachineIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      toMachineId_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 心跳扩展信息
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 心跳扩展信息
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 心跳扩展信息
     * </pre>
     *
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int checkSum_ ;
    /**
     * <pre>
     * 校验码(时间戳+机器ID)
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @return The checkSum.
     */
    @java.lang.Override
    public int getCheckSum() {
      return checkSum_;
    }
    /**
     * <pre>
     * 校验码(时间戳+机器ID)
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @param value The checkSum to set.
     * @return This builder for chaining.
     */
    public Builder setCheckSum(int value) {
      
      checkSum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 校验码(时间戳+机器ID)
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckSum() {
      
      checkSum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gm.link.common.domain.protobuf.ProtoHB)
  }

  // @@protoc_insertion_point(class_scope:com.gm.link.common.domain.protobuf.ProtoHB)
  private static final com.gm.link.common.domain.protobuf.ProtoHB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gm.link.common.domain.protobuf.ProtoHB();
  }

  public static com.gm.link.common.domain.protobuf.ProtoHB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoHB>
      PARSER = new com.google.protobuf.AbstractParser<ProtoHB>() {
    @java.lang.Override
    public ProtoHB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoHB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoHB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoHB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gm.link.common.domain.protobuf.ProtoHB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

