// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

public final class ProtoMessageOuter {
  private ProtoMessageOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessage.proto\022\"com.gm.link.common" +
      ".domain.protobuf\"\344\003\n\014ProtoMessage\022\r\n\005mag" +
      "ic\030\001 \001(\007\022\017\n\007version\030\002 \001(\r\022\013\n\003cmd\030\003 \001(\r\022\023" +
      "\n\013msg_feature\030\004 \001(\r\022\016\n\006msg_id\030\005 \001(\t\022\016\n\006s" +
      "eq_id\030\006 \001(\t\022\021\n\ttimestamp\030\007 \001(\003\022\024\n\014from_u" +
      "ser_id\030\010 \001(\t\022\027\n\nto_user_id\030\t \001(\tH\000\210\001\001\022\030\n" +
      "\013to_group_id\030\n \001(\tH\001\210\001\001\022A\n\010msg_type\030\013 \001(" +
      "\0162/.com.gm.link.common.domain.protobuf.M" +
      "essageType\022E\n\nmsg_status\030\014 \001(\01621.com.gm." +
      "link.common.domain.protobuf.MessageStatu" +
      "s\022\r\n\005flags\030\r \001(\r\022\030\n\013retry_count\030\016 \001(\rH\002\210" +
      "\001\001\022\023\n\013data_length\030\017 \001(\r\022\021\n\tcheck_sum\030\020 \001" +
      "(\007\022\014\n\004body\030\021 \001(\014B\r\n\013_to_user_idB\016\n\014_to_g" +
      "roup_idB\016\n\014_retry_count*t\n\013MessageType\022\017" +
      "\n\013MSG_UNKNOWN\020\000\022\014\n\010MSG_TEXT\020\001\022\r\n\tMSG_IMA" +
      "GE\020\002\022\r\n\tMSG_VOICE\020\003\022\r\n\tMSG_VIDEO\020\004\022\014\n\010MS" +
      "G_FILE\020\005\022\013\n\007MSG_CMD\020\006*[\n\rMessageStatus\022\022" +
      "\n\016STATUS_SENDING\020\000\022\017\n\013STATUS_SENT\020\001\022\024\n\020S" +
      "TATUS_DELIVERED\020\002\022\017\n\013STATUS_READ\020\003B9\n\"co" +
      "m.gm.link.common.domain.protobufB\021ProtoM" +
      "essageOuterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor,
        new java.lang.String[] { "Magic", "Version", "Cmd", "MsgFeature", "MsgId", "SeqId", "Timestamp", "FromUserId", "ToUserId", "ToGroupId", "MsgType", "MsgStatus", "Flags", "RetryCount", "DataLength", "CheckSum", "Body", "ToUserId", "ToGroupId", "RetryCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
