// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoMessage}
 */
public final class ProtoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gm.link.common.domain.protobuf.ProtoMessage)
    ProtoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoMessage.newBuilder() to construct.
  private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoMessage() {
    msgId_ = "";
    seqId_ = "";
    fromUserId_ = "";
    toUserId_ = "";
    toGroupId_ = "";
    msgType_ = 0;
    msgStatus_ = 0;
    body_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            magic_ = input.readFixed32();
            break;
          }
          case 16: {

            version_ = input.readUInt32();
            break;
          }
          case 24: {

            cmd_ = input.readUInt32();
            break;
          }
          case 32: {

            msgFeature_ = input.readUInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            msgId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            seqId_ = s;
            break;
          }
          case 56: {

            timestamp_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            fromUserId_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            toUserId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000002;
            toGroupId_ = s;
            break;
          }
          case 88: {
            int rawValue = input.readEnum();

            msgType_ = rawValue;
            break;
          }
          case 96: {
            int rawValue = input.readEnum();

            msgStatus_ = rawValue;
            break;
          }
          case 104: {

            flags_ = input.readUInt32();
            break;
          }
          case 112: {
            bitField0_ |= 0x00000004;
            retryCount_ = input.readUInt32();
            break;
          }
          case 120: {

            dataLength_ = input.readUInt32();
            break;
          }
          case 133: {

            checkSum_ = input.readFixed32();
            break;
          }
          case 138: {

            body_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.ProtoMessageOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gm.link.common.domain.protobuf.ProtoMessageOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gm.link.common.domain.protobuf.ProtoMessage.class, com.gm.link.common.domain.protobuf.ProtoMessage.Builder.class);
  }

  private int bitField0_;
  public static final int MAGIC_FIELD_NUMBER = 1;
  private int magic_;
  /**
   * <pre>
   * 固定头
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  @java.lang.Override
  public int getMagic() {
    return magic_;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_;
  /**
   * <pre>
   * 2字节协议版本
   * </pre>
   *
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int CMD_FIELD_NUMBER = 3;
  private int cmd_;
  /**
   * <pre>
   * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
   * </pre>
   *
   * <code>uint32 cmd = 3;</code>
   * @return The cmd.
   */
  @java.lang.Override
  public int getCmd() {
    return cmd_;
  }

  public static final int MSG_FEATURE_FIELD_NUMBER = 4;
  private int msgFeature_;
  /**
   * <pre>
   * 业务标识
   * </pre>
   *
   * <code>uint32 msg_feature = 4;</code>
   * @return The msgFeature.
   */
  @java.lang.Override
  public int getMsgFeature() {
    return msgFeature_;
  }

  public static final int MSG_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object msgId_;
  /**
   * <pre>
   * 消息元数据
   * </pre>
   *
   * <code>string msg_id = 5;</code>
   * @return The msgId.
   */
  @java.lang.Override
  public java.lang.String getMsgId() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      msgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 消息元数据
   * </pre>
   *
   * <code>string msg_id = 5;</code>
   * @return The bytes for msgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgIdBytes() {
    java.lang.Object ref = msgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEQ_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object seqId_;
  /**
   * <pre>
   * 会话内严格递增的序列号
   * </pre>
   *
   * <code>string seq_id = 6;</code>
   * @return The seqId.
   */
  @java.lang.Override
  public java.lang.String getSeqId() {
    java.lang.Object ref = seqId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      seqId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 会话内严格递增的序列号
   * </pre>
   *
   * <code>string seq_id = 6;</code>
   * @return The bytes for seqId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSeqIdBytes() {
    java.lang.Object ref = seqId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      seqId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 7;
  private long timestamp_;
  /**
   * <pre>
   * Unix时间戳(毫秒)
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int FROM_USER_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object fromUserId_;
  /**
   * <pre>
   * 发送方唯一标识
   * </pre>
   *
   * <code>string from_user_id = 8;</code>
   * @return The fromUserId.
   */
  @java.lang.Override
  public java.lang.String getFromUserId() {
    java.lang.Object ref = fromUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromUserId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 发送方唯一标识
   * </pre>
   *
   * <code>string from_user_id = 8;</code>
   * @return The bytes for fromUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFromUserIdBytes() {
    java.lang.Object ref = fromUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_USER_ID_FIELD_NUMBER = 9;
  private volatile java.lang.Object toUserId_;
  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return Whether the toUserId field is set.
   */
  @java.lang.Override
  public boolean hasToUserId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return The toUserId.
   */
  @java.lang.Override
  public java.lang.String getToUserId() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toUserId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return The bytes for toUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToUserIdBytes() {
    java.lang.Object ref = toUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TO_GROUP_ID_FIELD_NUMBER = 10;
  private volatile java.lang.Object toGroupId_;
  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return Whether the toGroupId field is set.
   */
  @java.lang.Override
  public boolean hasToGroupId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return The toGroupId.
   */
  @java.lang.Override
  public java.lang.String getToGroupId() {
    java.lang.Object ref = toGroupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      toGroupId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return The bytes for toGroupId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getToGroupIdBytes() {
    java.lang.Object ref = toGroupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      toGroupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSG_TYPE_FIELD_NUMBER = 11;
  private int msgType_;
  /**
   * <pre>
   * 消息属性
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  @java.lang.Override public int getMsgTypeValue() {
    return msgType_;
  }
  /**
   * <pre>
   * 消息属性
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
   * @return The msgType.
   */
  @java.lang.Override public com.gm.link.common.domain.protobuf.MessageType getMsgType() {
    @SuppressWarnings("deprecation")
    com.gm.link.common.domain.protobuf.MessageType result = com.gm.link.common.domain.protobuf.MessageType.valueOf(msgType_);
    return result == null ? com.gm.link.common.domain.protobuf.MessageType.UNRECOGNIZED : result;
  }

  public static final int MSG_STATUS_FIELD_NUMBER = 12;
  private int msgStatus_;
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
   * @return The enum numeric value on the wire for msgStatus.
   */
  @java.lang.Override public int getMsgStatusValue() {
    return msgStatus_;
  }
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
   * @return The msgStatus.
   */
  @java.lang.Override public com.gm.link.common.domain.protobuf.MessageStatus getMsgStatus() {
    @SuppressWarnings("deprecation")
    com.gm.link.common.domain.protobuf.MessageStatus result = com.gm.link.common.domain.protobuf.MessageStatus.valueOf(msgStatus_);
    return result == null ? com.gm.link.common.domain.protobuf.MessageStatus.UNRECOGNIZED : result;
  }

  public static final int FLAGS_FIELD_NUMBER = 13;
  private int flags_;
  /**
   * <pre>
   * 2字节标志位(bit0=是否需要ACK)
   * </pre>
   *
   * <code>uint32 flags = 13;</code>
   * @return The flags.
   */
  @java.lang.Override
  public int getFlags() {
    return flags_;
  }

  public static final int RETRY_COUNT_FIELD_NUMBER = 14;
  private int retryCount_;
  /**
   * <pre>
   * [可选]重试次数(0-255)
   * </pre>
   *
   * <code>optional uint32 retry_count = 14;</code>
   * @return Whether the retryCount field is set.
   */
  @java.lang.Override
  public boolean hasRetryCount() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * [可选]重试次数(0-255)
   * </pre>
   *
   * <code>optional uint32 retry_count = 14;</code>
   * @return The retryCount.
   */
  @java.lang.Override
  public int getRetryCount() {
    return retryCount_;
  }

  public static final int DATA_LENGTH_FIELD_NUMBER = 15;
  private int dataLength_;
  /**
   * <pre>
   * 数据校验
   * </pre>
   *
   * <code>uint32 data_length = 15;</code>
   * @return The dataLength.
   */
  @java.lang.Override
  public int getDataLength() {
    return dataLength_;
  }

  public static final int CHECK_SUM_FIELD_NUMBER = 16;
  private int checkSum_;
  /**
   * <pre>
   * 4字节校验码(CRC32)
   * </pre>
   *
   * <code>fixed32 check_sum = 16;</code>
   * @return The checkSum.
   */
  @java.lang.Override
  public int getCheckSum() {
    return checkSum_;
  }

  public static final int BODY_FIELD_NUMBER = 17;
  private com.google.protobuf.ByteString body_;
  /**
   * <pre>
   * Protobuf序列化后的业务数据
   * </pre>
   *
   * <code>bytes body = 17;</code>
   * @return The body.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getBody() {
    return body_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (magic_ != 0) {
      output.writeFixed32(1, magic_);
    }
    if (version_ != 0) {
      output.writeUInt32(2, version_);
    }
    if (cmd_ != 0) {
      output.writeUInt32(3, cmd_);
    }
    if (msgFeature_ != 0) {
      output.writeUInt32(4, msgFeature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seqId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, seqId_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUserId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fromUserId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, toUserId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, toGroupId_);
    }
    if (msgType_ != com.gm.link.common.domain.protobuf.MessageType.MSG_UNKNOWN.getNumber()) {
      output.writeEnum(11, msgType_);
    }
    if (msgStatus_ != com.gm.link.common.domain.protobuf.MessageStatus.STATUS_SENDING.getNumber()) {
      output.writeEnum(12, msgStatus_);
    }
    if (flags_ != 0) {
      output.writeUInt32(13, flags_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeUInt32(14, retryCount_);
    }
    if (dataLength_ != 0) {
      output.writeUInt32(15, dataLength_);
    }
    if (checkSum_ != 0) {
      output.writeFixed32(16, checkSum_);
    }
    if (!body_.isEmpty()) {
      output.writeBytes(17, body_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (magic_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, magic_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, version_);
    }
    if (cmd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, cmd_);
    }
    if (msgFeature_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, msgFeature_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(seqId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, seqId_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, timestamp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fromUserId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fromUserId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, toUserId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, toGroupId_);
    }
    if (msgType_ != com.gm.link.common.domain.protobuf.MessageType.MSG_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(11, msgType_);
    }
    if (msgStatus_ != com.gm.link.common.domain.protobuf.MessageStatus.STATUS_SENDING.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, msgStatus_);
    }
    if (flags_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(13, flags_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(14, retryCount_);
    }
    if (dataLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(15, dataLength_);
    }
    if (checkSum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(16, checkSum_);
    }
    if (!body_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, body_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gm.link.common.domain.protobuf.ProtoMessage)) {
      return super.equals(obj);
    }
    com.gm.link.common.domain.protobuf.ProtoMessage other = (com.gm.link.common.domain.protobuf.ProtoMessage) obj;

    if (getMagic()
        != other.getMagic()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getCmd()
        != other.getCmd()) return false;
    if (getMsgFeature()
        != other.getMsgFeature()) return false;
    if (!getMsgId()
        .equals(other.getMsgId())) return false;
    if (!getSeqId()
        .equals(other.getSeqId())) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getFromUserId()
        .equals(other.getFromUserId())) return false;
    if (hasToUserId() != other.hasToUserId()) return false;
    if (hasToUserId()) {
      if (!getToUserId()
          .equals(other.getToUserId())) return false;
    }
    if (hasToGroupId() != other.hasToGroupId()) return false;
    if (hasToGroupId()) {
      if (!getToGroupId()
          .equals(other.getToGroupId())) return false;
    }
    if (msgType_ != other.msgType_) return false;
    if (msgStatus_ != other.msgStatus_) return false;
    if (getFlags()
        != other.getFlags()) return false;
    if (hasRetryCount() != other.hasRetryCount()) return false;
    if (hasRetryCount()) {
      if (getRetryCount()
          != other.getRetryCount()) return false;
    }
    if (getDataLength()
        != other.getDataLength()) return false;
    if (getCheckSum()
        != other.getCheckSum()) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAGIC_FIELD_NUMBER;
    hash = (53 * hash) + getMagic();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd();
    hash = (37 * hash) + MSG_FEATURE_FIELD_NUMBER;
    hash = (53 * hash) + getMsgFeature();
    hash = (37 * hash) + MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId().hashCode();
    hash = (37 * hash) + SEQ_ID_FIELD_NUMBER;
    hash = (53 * hash) + getSeqId().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + FROM_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getFromUserId().hashCode();
    if (hasToUserId()) {
      hash = (37 * hash) + TO_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
    }
    if (hasToGroupId()) {
      hash = (37 * hash) + TO_GROUP_ID_FIELD_NUMBER;
      hash = (53 * hash) + getToGroupId().hashCode();
    }
    hash = (37 * hash) + MSG_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + msgType_;
    hash = (37 * hash) + MSG_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + msgStatus_;
    hash = (37 * hash) + FLAGS_FIELD_NUMBER;
    hash = (53 * hash) + getFlags();
    if (hasRetryCount()) {
      hash = (37 * hash) + RETRY_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getRetryCount();
    }
    hash = (37 * hash) + DATA_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getDataLength();
    hash = (37 * hash) + CHECK_SUM_FIELD_NUMBER;
    hash = (53 * hash) + getCheckSum();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gm.link.common.domain.protobuf.ProtoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gm.link.common.domain.protobuf.ProtoMessage)
      com.gm.link.common.domain.protobuf.ProtoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.link.common.domain.protobuf.ProtoMessageOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.link.common.domain.protobuf.ProtoMessageOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.link.common.domain.protobuf.ProtoMessage.class, com.gm.link.common.domain.protobuf.ProtoMessage.Builder.class);
    }

    // Construct using com.gm.link.common.domain.protobuf.ProtoMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      magic_ = 0;

      version_ = 0;

      cmd_ = 0;

      msgFeature_ = 0;

      msgId_ = "";

      seqId_ = "";

      timestamp_ = 0L;

      fromUserId_ = "";

      toUserId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      toGroupId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      msgType_ = 0;

      msgStatus_ = 0;

      flags_ = 0;

      retryCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      dataLength_ = 0;

      checkSum_ = 0;

      body_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gm.link.common.domain.protobuf.ProtoMessageOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoMessage getDefaultInstanceForType() {
      return com.gm.link.common.domain.protobuf.ProtoMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoMessage build() {
      com.gm.link.common.domain.protobuf.ProtoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoMessage buildPartial() {
      com.gm.link.common.domain.protobuf.ProtoMessage result = new com.gm.link.common.domain.protobuf.ProtoMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.magic_ = magic_;
      result.version_ = version_;
      result.cmd_ = cmd_;
      result.msgFeature_ = msgFeature_;
      result.msgId_ = msgId_;
      result.seqId_ = seqId_;
      result.timestamp_ = timestamp_;
      result.fromUserId_ = fromUserId_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.toUserId_ = toUserId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.toGroupId_ = toGroupId_;
      result.msgType_ = msgType_;
      result.msgStatus_ = msgStatus_;
      result.flags_ = flags_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.retryCount_ = retryCount_;
        to_bitField0_ |= 0x00000004;
      }
      result.dataLength_ = dataLength_;
      result.checkSum_ = checkSum_;
      result.body_ = body_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gm.link.common.domain.protobuf.ProtoMessage) {
        return mergeFrom((com.gm.link.common.domain.protobuf.ProtoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gm.link.common.domain.protobuf.ProtoMessage other) {
      if (other == com.gm.link.common.domain.protobuf.ProtoMessage.getDefaultInstance()) return this;
      if (other.getMagic() != 0) {
        setMagic(other.getMagic());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCmd() != 0) {
        setCmd(other.getCmd());
      }
      if (other.getMsgFeature() != 0) {
        setMsgFeature(other.getMsgFeature());
      }
      if (!other.getMsgId().isEmpty()) {
        msgId_ = other.msgId_;
        onChanged();
      }
      if (!other.getSeqId().isEmpty()) {
        seqId_ = other.seqId_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (!other.getFromUserId().isEmpty()) {
        fromUserId_ = other.fromUserId_;
        onChanged();
      }
      if (other.hasToUserId()) {
        bitField0_ |= 0x00000001;
        toUserId_ = other.toUserId_;
        onChanged();
      }
      if (other.hasToGroupId()) {
        bitField0_ |= 0x00000002;
        toGroupId_ = other.toGroupId_;
        onChanged();
      }
      if (other.msgType_ != 0) {
        setMsgTypeValue(other.getMsgTypeValue());
      }
      if (other.msgStatus_ != 0) {
        setMsgStatusValue(other.getMsgStatusValue());
      }
      if (other.getFlags() != 0) {
        setFlags(other.getFlags());
      }
      if (other.hasRetryCount()) {
        setRetryCount(other.getRetryCount());
      }
      if (other.getDataLength() != 0) {
        setDataLength(other.getDataLength());
      }
      if (other.getCheckSum() != 0) {
        setCheckSum(other.getCheckSum());
      }
      if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
        setBody(other.getBody());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gm.link.common.domain.protobuf.ProtoMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gm.link.common.domain.protobuf.ProtoMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int magic_ ;
    /**
     * <pre>
     * 固定头
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return The magic.
     */
    @java.lang.Override
    public int getMagic() {
      return magic_;
    }
    /**
     * <pre>
     * 固定头
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @param value The magic to set.
     * @return This builder for chaining.
     */
    public Builder setMagic(int value) {
      
      magic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 固定头
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMagic() {
      
      magic_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     * 2字节协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * 2字节协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private int cmd_ ;
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
      return cmd_;
    }
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(int value) {
      
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private int msgFeature_ ;
    /**
     * <pre>
     * 业务标识
     * </pre>
     *
     * <code>uint32 msg_feature = 4;</code>
     * @return The msgFeature.
     */
    @java.lang.Override
    public int getMsgFeature() {
      return msgFeature_;
    }
    /**
     * <pre>
     * 业务标识
     * </pre>
     *
     * <code>uint32 msg_feature = 4;</code>
     * @param value The msgFeature to set.
     * @return This builder for chaining.
     */
    public Builder setMsgFeature(int value) {
      
      msgFeature_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 业务标识
     * </pre>
     *
     * <code>uint32 msg_feature = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgFeature() {
      
      msgFeature_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object msgId_ = "";
    /**
     * <pre>
     * 消息元数据
     * </pre>
     *
     * <code>string msg_id = 5;</code>
     * @return The msgId.
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 消息元数据
     * </pre>
     *
     * <code>string msg_id = 5;</code>
     * @return The bytes for msgId.
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 消息元数据
     * </pre>
     *
     * <code>string msg_id = 5;</code>
     * @param value The msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      msgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息元数据
     * </pre>
     *
     * <code>string msg_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgId() {
      
      msgId_ = getDefaultInstance().getMsgId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息元数据
     * </pre>
     *
     * <code>string msg_id = 5;</code>
     * @param value The bytes for msgId to set.
     * @return This builder for chaining.
     */
    public Builder setMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      msgId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object seqId_ = "";
    /**
     * <pre>
     * 会话内严格递增的序列号
     * </pre>
     *
     * <code>string seq_id = 6;</code>
     * @return The seqId.
     */
    public java.lang.String getSeqId() {
      java.lang.Object ref = seqId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        seqId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 会话内严格递增的序列号
     * </pre>
     *
     * <code>string seq_id = 6;</code>
     * @return The bytes for seqId.
     */
    public com.google.protobuf.ByteString
        getSeqIdBytes() {
      java.lang.Object ref = seqId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        seqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 会话内严格递增的序列号
     * </pre>
     *
     * <code>string seq_id = 6;</code>
     * @param value The seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      seqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话内严格递增的序列号
     * </pre>
     *
     * <code>string seq_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeqId() {
      
      seqId_ = getDefaultInstance().getSeqId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 会话内严格递增的序列号
     * </pre>
     *
     * <code>string seq_id = 6;</code>
     * @param value The bytes for seqId to set.
     * @return This builder for chaining.
     */
    public Builder setSeqIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      seqId_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * Unix时间戳(毫秒)
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * Unix时间戳(毫秒)
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unix时间戳(毫秒)
     * </pre>
     *
     * <code>int64 timestamp = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object fromUserId_ = "";
    /**
     * <pre>
     * 发送方唯一标识
     * </pre>
     *
     * <code>string from_user_id = 8;</code>
     * @return The fromUserId.
     */
    public java.lang.String getFromUserId() {
      java.lang.Object ref = fromUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 发送方唯一标识
     * </pre>
     *
     * <code>string from_user_id = 8;</code>
     * @return The bytes for fromUserId.
     */
    public com.google.protobuf.ByteString
        getFromUserIdBytes() {
      java.lang.Object ref = fromUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 发送方唯一标识
     * </pre>
     *
     * <code>string from_user_id = 8;</code>
     * @param value The fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送方唯一标识
     * </pre>
     *
     * <code>string from_user_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFromUserId() {
      
      fromUserId_ = getDefaultInstance().getFromUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 发送方唯一标识
     * </pre>
     *
     * <code>string from_user_id = 8;</code>
     * @param value The bytes for fromUserId to set.
     * @return This builder for chaining.
     */
    public Builder setFromUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toUserId_ = "";
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @return Whether the toUserId field is set.
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @return The toUserId.
     */
    public java.lang.String getToUserId() {
      java.lang.Object ref = toUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @return The bytes for toUserId.
     */
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      java.lang.Object ref = toUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @param value The toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      toUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearToUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      toUserId_ = getDefaultInstance().getToUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]私聊对象ID
     * </pre>
     *
     * <code>optional string to_user_id = 9;</code>
     * @param value The bytes for toUserId to set.
     * @return This builder for chaining.
     */
    public Builder setToUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      toUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object toGroupId_ = "";
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @return Whether the toGroupId field is set.
     */
    public boolean hasToGroupId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @return The toGroupId.
     */
    public java.lang.String getToGroupId() {
      java.lang.Object ref = toGroupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toGroupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @return The bytes for toGroupId.
     */
    public com.google.protobuf.ByteString
        getToGroupIdBytes() {
      java.lang.Object ref = toGroupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @param value The toGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setToGroupId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      toGroupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearToGroupId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      toGroupId_ = getDefaultInstance().getToGroupId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]接收群聊ID
     * </pre>
     *
     * <code>optional string to_group_id = 10;</code>
     * @param value The bytes for toGroupId to set.
     * @return This builder for chaining.
     */
    public Builder setToGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      toGroupId_ = value;
      onChanged();
      return this;
    }

    private int msgType_ = 0;
    /**
     * <pre>
     * 消息属性
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @java.lang.Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <pre>
     * 消息属性
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
     * @param value The enum numeric value on the wire for msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgTypeValue(int value) {
      
      msgType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息属性
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
     * @return The msgType.
     */
    @java.lang.Override
    public com.gm.link.common.domain.protobuf.MessageType getMsgType() {
      @SuppressWarnings("deprecation")
      com.gm.link.common.domain.protobuf.MessageType result = com.gm.link.common.domain.protobuf.MessageType.valueOf(msgType_);
      return result == null ? com.gm.link.common.domain.protobuf.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息属性
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
     * @param value The msgType to set.
     * @return This builder for chaining.
     */
    public Builder setMsgType(com.gm.link.common.domain.protobuf.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msgType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息属性
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgType() {
      
      msgType_ = 0;
      onChanged();
      return this;
    }

    private int msgStatus_ = 0;
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
     * @return The enum numeric value on the wire for msgStatus.
     */
    @java.lang.Override public int getMsgStatusValue() {
      return msgStatus_;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
     * @param value The enum numeric value on the wire for msgStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMsgStatusValue(int value) {
      
      msgStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
     * @return The msgStatus.
     */
    @java.lang.Override
    public com.gm.link.common.domain.protobuf.MessageStatus getMsgStatus() {
      @SuppressWarnings("deprecation")
      com.gm.link.common.domain.protobuf.MessageStatus result = com.gm.link.common.domain.protobuf.MessageStatus.valueOf(msgStatus_);
      return result == null ? com.gm.link.common.domain.protobuf.MessageStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
     * @param value The msgStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMsgStatus(com.gm.link.common.domain.protobuf.MessageStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msgStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息状态
     * </pre>
     *
     * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgStatus() {
      
      msgStatus_ = 0;
      onChanged();
      return this;
    }

    private int flags_ ;
    /**
     * <pre>
     * 2字节标志位(bit0=是否需要ACK)
     * </pre>
     *
     * <code>uint32 flags = 13;</code>
     * @return The flags.
     */
    @java.lang.Override
    public int getFlags() {
      return flags_;
    }
    /**
     * <pre>
     * 2字节标志位(bit0=是否需要ACK)
     * </pre>
     *
     * <code>uint32 flags = 13;</code>
     * @param value The flags to set.
     * @return This builder for chaining.
     */
    public Builder setFlags(int value) {
      
      flags_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节标志位(bit0=是否需要ACK)
     * </pre>
     *
     * <code>uint32 flags = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearFlags() {
      
      flags_ = 0;
      onChanged();
      return this;
    }

    private int retryCount_ ;
    /**
     * <pre>
     * [可选]重试次数(0-255)
     * </pre>
     *
     * <code>optional uint32 retry_count = 14;</code>
     * @return Whether the retryCount field is set.
     */
    @java.lang.Override
    public boolean hasRetryCount() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * [可选]重试次数(0-255)
     * </pre>
     *
     * <code>optional uint32 retry_count = 14;</code>
     * @return The retryCount.
     */
    @java.lang.Override
    public int getRetryCount() {
      return retryCount_;
    }
    /**
     * <pre>
     * [可选]重试次数(0-255)
     * </pre>
     *
     * <code>optional uint32 retry_count = 14;</code>
     * @param value The retryCount to set.
     * @return This builder for chaining.
     */
    public Builder setRetryCount(int value) {
      bitField0_ |= 0x00000004;
      retryCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]重试次数(0-255)
     * </pre>
     *
     * <code>optional uint32 retry_count = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetryCount() {
      bitField0_ = (bitField0_ & ~0x00000004);
      retryCount_ = 0;
      onChanged();
      return this;
    }

    private int dataLength_ ;
    /**
     * <pre>
     * 数据校验
     * </pre>
     *
     * <code>uint32 data_length = 15;</code>
     * @return The dataLength.
     */
    @java.lang.Override
    public int getDataLength() {
      return dataLength_;
    }
    /**
     * <pre>
     * 数据校验
     * </pre>
     *
     * <code>uint32 data_length = 15;</code>
     * @param value The dataLength to set.
     * @return This builder for chaining.
     */
    public Builder setDataLength(int value) {
      
      dataLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据校验
     * </pre>
     *
     * <code>uint32 data_length = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearDataLength() {
      
      dataLength_ = 0;
      onChanged();
      return this;
    }

    private int checkSum_ ;
    /**
     * <pre>
     * 4字节校验码(CRC32)
     * </pre>
     *
     * <code>fixed32 check_sum = 16;</code>
     * @return The checkSum.
     */
    @java.lang.Override
    public int getCheckSum() {
      return checkSum_;
    }
    /**
     * <pre>
     * 4字节校验码(CRC32)
     * </pre>
     *
     * <code>fixed32 check_sum = 16;</code>
     * @param value The checkSum to set.
     * @return This builder for chaining.
     */
    public Builder setCheckSum(int value) {
      
      checkSum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 4字节校验码(CRC32)
     * </pre>
     *
     * <code>fixed32 check_sum = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckSum() {
      
      checkSum_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Protobuf序列化后的业务数据
     * </pre>
     *
     * <code>bytes body = 17;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }
    /**
     * <pre>
     * Protobuf序列化后的业务数据
     * </pre>
     *
     * <code>bytes body = 17;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Protobuf序列化后的业务数据
     * </pre>
     *
     * <code>bytes body = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gm.link.common.domain.protobuf.ProtoMessage)
  }

  // @@protoc_insertion_point(class_scope:com.gm.link.common.domain.protobuf.ProtoMessage)
  private static final com.gm.link.common.domain.protobuf.ProtoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gm.link.common.domain.protobuf.ProtoMessage();
  }

  public static com.gm.link.common.domain.protobuf.ProtoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
    @java.lang.Override
    public ProtoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gm.link.common.domain.protobuf.ProtoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

