// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

public interface ProtoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gm.link.common.domain.protobuf.ProtoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 固定头
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  int getMagic();

  /**
   * <pre>
   * 2字节协议版本
   * </pre>
   *
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * 2字节命令字,0x0001-业务消息，0x0002-ack，0x0003-心跳
   * </pre>
   *
   * <code>uint32 cmd = 3;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <pre>
   * 业务标识
   * </pre>
   *
   * <code>uint32 msg_feature = 4;</code>
   * @return The msgFeature.
   */
  int getMsgFeature();

  /**
   * <pre>
   * 消息元数据
   * </pre>
   *
   * <code>string msg_id = 5;</code>
   * @return The msgId.
   */
  java.lang.String getMsgId();
  /**
   * <pre>
   * 消息元数据
   * </pre>
   *
   * <code>string msg_id = 5;</code>
   * @return The bytes for msgId.
   */
  com.google.protobuf.ByteString
      getMsgIdBytes();

  /**
   * <pre>
   * 会话内严格递增的序列号
   * </pre>
   *
   * <code>string seq_id = 6;</code>
   * @return The seqId.
   */
  java.lang.String getSeqId();
  /**
   * <pre>
   * 会话内严格递增的序列号
   * </pre>
   *
   * <code>string seq_id = 6;</code>
   * @return The bytes for seqId.
   */
  com.google.protobuf.ByteString
      getSeqIdBytes();

  /**
   * <pre>
   * Unix时间戳(毫秒)
   * </pre>
   *
   * <code>int64 timestamp = 7;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 发送方唯一标识
   * </pre>
   *
   * <code>string from_user_id = 8;</code>
   * @return The fromUserId.
   */
  java.lang.String getFromUserId();
  /**
   * <pre>
   * 发送方唯一标识
   * </pre>
   *
   * <code>string from_user_id = 8;</code>
   * @return The bytes for fromUserId.
   */
  com.google.protobuf.ByteString
      getFromUserIdBytes();

  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return Whether the toUserId field is set.
   */
  boolean hasToUserId();
  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return The toUserId.
   */
  java.lang.String getToUserId();
  /**
   * <pre>
   * [可选]私聊对象ID
   * </pre>
   *
   * <code>optional string to_user_id = 9;</code>
   * @return The bytes for toUserId.
   */
  com.google.protobuf.ByteString
      getToUserIdBytes();

  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return Whether the toGroupId field is set.
   */
  boolean hasToGroupId();
  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return The toGroupId.
   */
  java.lang.String getToGroupId();
  /**
   * <pre>
   * [可选]接收群聊ID
   * </pre>
   *
   * <code>optional string to_group_id = 10;</code>
   * @return The bytes for toGroupId.
   */
  com.google.protobuf.ByteString
      getToGroupIdBytes();

  /**
   * <pre>
   * 消息属性
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
   * @return The enum numeric value on the wire for msgType.
   */
  int getMsgTypeValue();
  /**
   * <pre>
   * 消息属性
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageType msg_type = 11;</code>
   * @return The msgType.
   */
  com.gm.link.common.domain.protobuf.MessageType getMsgType();

  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
   * @return The enum numeric value on the wire for msgStatus.
   */
  int getMsgStatusValue();
  /**
   * <pre>
   * 消息状态
   * </pre>
   *
   * <code>.com.gm.link.common.domain.protobuf.MessageStatus msg_status = 12;</code>
   * @return The msgStatus.
   */
  com.gm.link.common.domain.protobuf.MessageStatus getMsgStatus();

  /**
   * <pre>
   * 2字节标志位(bit0=是否需要ACK)
   * </pre>
   *
   * <code>uint32 flags = 13;</code>
   * @return The flags.
   */
  int getFlags();

  /**
   * <pre>
   * [可选]重试次数(0-255)
   * </pre>
   *
   * <code>optional uint32 retry_count = 14;</code>
   * @return Whether the retryCount field is set.
   */
  boolean hasRetryCount();
  /**
   * <pre>
   * [可选]重试次数(0-255)
   * </pre>
   *
   * <code>optional uint32 retry_count = 14;</code>
   * @return The retryCount.
   */
  int getRetryCount();

  /**
   * <pre>
   * 数据校验
   * </pre>
   *
   * <code>uint32 data_length = 15;</code>
   * @return The dataLength.
   */
  int getDataLength();

  /**
   * <pre>
   * 4字节校验码(CRC32)
   * </pre>
   *
   * <code>fixed32 check_sum = 16;</code>
   * @return The checkSum.
   */
  int getCheckSum();

  /**
   * <pre>
   * Protobuf序列化后的业务数据
   * </pre>
   *
   * <code>bytes body = 17;</code>
   * @return The body.
   */
  com.google.protobuf.ByteString getBody();
}
