// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoAck.proto

package com.gm.link.common.domain.protobuf;

/**
 * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoAck}
 */
public final class ProtoAck extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.gm.link.common.domain.protobuf.ProtoAck)
    ProtoAckOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProtoAck.newBuilder() to construct.
  private ProtoAck(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProtoAck() {
    originalMsgId_ = "";
    errorMsg_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProtoAck();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProtoAck(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            magic_ = input.readFixed32();
            break;
          }
          case 16: {

            version_ = input.readUInt32();
            break;
          }
          case 24: {

            cmd_ = input.readUInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            originalMsgId_ = s;
            break;
          }
          case 40: {

            status_ = input.readUInt32();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000001;
            errorMsg_ = s;
            break;
          }
          case 61: {

            checkSum_ = input.readFixed32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gm.link.common.domain.protobuf.ProtoAckOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoAck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gm.link.common.domain.protobuf.ProtoAckOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gm.link.common.domain.protobuf.ProtoAck.class, com.gm.link.common.domain.protobuf.ProtoAck.Builder.class);
  }

  private int bitField0_;
  public static final int MAGIC_FIELD_NUMBER = 1;
  private int magic_;
  /**
   * <pre>
   * 4字节魔数(必须与请求一致)
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  @java.lang.Override
  public int getMagic() {
    return magic_;
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private int version_;
  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int CMD_FIELD_NUMBER = 3;
  private int cmd_;
  /**
   * <pre>
   * 固定为0x0002
   * </pre>
   *
   * <code>uint32 cmd = 3;</code>
   * @return The cmd.
   */
  @java.lang.Override
  public int getCmd() {
    return cmd_;
  }

  public static final int ORIGINAL_MSG_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object originalMsgId_;
  /**
   * <pre>
   * 需要确认的原消息ID
   * </pre>
   *
   * <code>string original_msg_id = 4;</code>
   * @return The originalMsgId.
   */
  @java.lang.Override
  public java.lang.String getOriginalMsgId() {
    java.lang.Object ref = originalMsgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      originalMsgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 需要确认的原消息ID
   * </pre>
   *
   * <code>string original_msg_id = 4;</code>
   * @return The bytes for originalMsgId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriginalMsgIdBytes() {
    java.lang.Object ref = originalMsgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      originalMsgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 5;
  private int status_;
  /**
   * <pre>
   * 2字节状态码，0-成功，其他-错误码
   * </pre>
   *
   * <code>uint32 status = 5;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int ERROR_MSG_FIELD_NUMBER = 6;
  private volatile java.lang.Object errorMsg_;
  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return Whether the errorMsg field is set.
   */
  @java.lang.Override
  public boolean hasErrorMsg() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return The errorMsg.
   */
  @java.lang.Override
  public java.lang.String getErrorMsg() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMsg_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return The bytes for errorMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMsgBytes() {
    java.lang.Object ref = errorMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECK_SUM_FIELD_NUMBER = 7;
  private int checkSum_;
  /**
   * <pre>
   * 扩展校验字段
   * </pre>
   *
   * <code>fixed32 check_sum = 7;</code>
   * @return The checkSum.
   */
  @java.lang.Override
  public int getCheckSum() {
    return checkSum_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (magic_ != 0) {
      output.writeFixed32(1, magic_);
    }
    if (version_ != 0) {
      output.writeUInt32(2, version_);
    }
    if (cmd_ != 0) {
      output.writeUInt32(3, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalMsgId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, originalMsgId_);
    }
    if (status_ != 0) {
      output.writeUInt32(5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, errorMsg_);
    }
    if (checkSum_ != 0) {
      output.writeFixed32(7, checkSum_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (magic_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(1, magic_);
    }
    if (version_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, version_);
    }
    if (cmd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, cmd_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(originalMsgId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, originalMsgId_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, errorMsg_);
    }
    if (checkSum_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed32Size(7, checkSum_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gm.link.common.domain.protobuf.ProtoAck)) {
      return super.equals(obj);
    }
    com.gm.link.common.domain.protobuf.ProtoAck other = (com.gm.link.common.domain.protobuf.ProtoAck) obj;

    if (getMagic()
        != other.getMagic()) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (getCmd()
        != other.getCmd()) return false;
    if (!getOriginalMsgId()
        .equals(other.getOriginalMsgId())) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (hasErrorMsg() != other.hasErrorMsg()) return false;
    if (hasErrorMsg()) {
      if (!getErrorMsg()
          .equals(other.getErrorMsg())) return false;
    }
    if (getCheckSum()
        != other.getCheckSum()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAGIC_FIELD_NUMBER;
    hash = (53 * hash) + getMagic();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd();
    hash = (37 * hash) + ORIGINAL_MSG_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOriginalMsgId().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    if (hasErrorMsg()) {
      hash = (37 * hash) + ERROR_MSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMsg().hashCode();
    }
    hash = (37 * hash) + CHECK_SUM_FIELD_NUMBER;
    hash = (53 * hash) + getCheckSum();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gm.link.common.domain.protobuf.ProtoAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gm.link.common.domain.protobuf.ProtoAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.gm.link.common.domain.protobuf.ProtoAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.gm.link.common.domain.protobuf.ProtoAck)
      com.gm.link.common.domain.protobuf.ProtoAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gm.link.common.domain.protobuf.ProtoAckOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gm.link.common.domain.protobuf.ProtoAckOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gm.link.common.domain.protobuf.ProtoAck.class, com.gm.link.common.domain.protobuf.ProtoAck.Builder.class);
    }

    // Construct using com.gm.link.common.domain.protobuf.ProtoAck.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      magic_ = 0;

      version_ = 0;

      cmd_ = 0;

      originalMsgId_ = "";

      status_ = 0;

      errorMsg_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      checkSum_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gm.link.common.domain.protobuf.ProtoAckOuter.internal_static_com_gm_link_common_domain_protobuf_ProtoAck_descriptor;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoAck getDefaultInstanceForType() {
      return com.gm.link.common.domain.protobuf.ProtoAck.getDefaultInstance();
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoAck build() {
      com.gm.link.common.domain.protobuf.ProtoAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gm.link.common.domain.protobuf.ProtoAck buildPartial() {
      com.gm.link.common.domain.protobuf.ProtoAck result = new com.gm.link.common.domain.protobuf.ProtoAck(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.magic_ = magic_;
      result.version_ = version_;
      result.cmd_ = cmd_;
      result.originalMsgId_ = originalMsgId_;
      result.status_ = status_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.errorMsg_ = errorMsg_;
      result.checkSum_ = checkSum_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gm.link.common.domain.protobuf.ProtoAck) {
        return mergeFrom((com.gm.link.common.domain.protobuf.ProtoAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gm.link.common.domain.protobuf.ProtoAck other) {
      if (other == com.gm.link.common.domain.protobuf.ProtoAck.getDefaultInstance()) return this;
      if (other.getMagic() != 0) {
        setMagic(other.getMagic());
      }
      if (other.getVersion() != 0) {
        setVersion(other.getVersion());
      }
      if (other.getCmd() != 0) {
        setCmd(other.getCmd());
      }
      if (!other.getOriginalMsgId().isEmpty()) {
        originalMsgId_ = other.originalMsgId_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.hasErrorMsg()) {
        bitField0_ |= 0x00000001;
        errorMsg_ = other.errorMsg_;
        onChanged();
      }
      if (other.getCheckSum() != 0) {
        setCheckSum(other.getCheckSum());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gm.link.common.domain.protobuf.ProtoAck parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gm.link.common.domain.protobuf.ProtoAck) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int magic_ ;
    /**
     * <pre>
     * 4字节魔数(必须与请求一致)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return The magic.
     */
    @java.lang.Override
    public int getMagic() {
      return magic_;
    }
    /**
     * <pre>
     * 4字节魔数(必须与请求一致)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @param value The magic to set.
     * @return This builder for chaining.
     */
    public Builder setMagic(int value) {
      
      magic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 4字节魔数(必须与请求一致)
     * </pre>
     *
     * <code>fixed32 magic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMagic() {
      
      magic_ = 0;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 协议版本
     * </pre>
     *
     * <code>uint32 version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = 0;
      onChanged();
      return this;
    }

    private int cmd_ ;
    /**
     * <pre>
     * 固定为0x0002
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @return The cmd.
     */
    @java.lang.Override
    public int getCmd() {
      return cmd_;
    }
    /**
     * <pre>
     * 固定为0x0002
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(int value) {
      
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 固定为0x0002
     * </pre>
     *
     * <code>uint32 cmd = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object originalMsgId_ = "";
    /**
     * <pre>
     * 需要确认的原消息ID
     * </pre>
     *
     * <code>string original_msg_id = 4;</code>
     * @return The originalMsgId.
     */
    public java.lang.String getOriginalMsgId() {
      java.lang.Object ref = originalMsgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        originalMsgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 需要确认的原消息ID
     * </pre>
     *
     * <code>string original_msg_id = 4;</code>
     * @return The bytes for originalMsgId.
     */
    public com.google.protobuf.ByteString
        getOriginalMsgIdBytes() {
      java.lang.Object ref = originalMsgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        originalMsgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 需要确认的原消息ID
     * </pre>
     *
     * <code>string original_msg_id = 4;</code>
     * @param value The originalMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalMsgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      originalMsgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 需要确认的原消息ID
     * </pre>
     *
     * <code>string original_msg_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriginalMsgId() {
      
      originalMsgId_ = getDefaultInstance().getOriginalMsgId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 需要确认的原消息ID
     * </pre>
     *
     * <code>string original_msg_id = 4;</code>
     * @param value The bytes for originalMsgId to set.
     * @return This builder for chaining.
     */
    public Builder setOriginalMsgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      originalMsgId_ = value;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     * 2字节状态码，0-成功，其他-错误码
     * </pre>
     *
     * <code>uint32 status = 5;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     * 2字节状态码，0-成功，其他-错误码
     * </pre>
     *
     * <code>uint32 status = 5;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 2字节状态码，0-成功，其他-错误码
     * </pre>
     *
     * <code>uint32 status = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object errorMsg_ = "";
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @return Whether the errorMsg field is set.
     */
    public boolean hasErrorMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @return The errorMsg.
     */
    public java.lang.String getErrorMsg() {
      java.lang.Object ref = errorMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @return The bytes for errorMsg.
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes() {
      java.lang.Object ref = errorMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @param value The errorMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      errorMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMsg() {
      bitField0_ = (bitField0_ & ~0x00000001);
      errorMsg_ = getDefaultInstance().getErrorMsg();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * [可选]错误描述
     * </pre>
     *
     * <code>optional string error_msg = 6;</code>
     * @param value The bytes for errorMsg to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      errorMsg_ = value;
      onChanged();
      return this;
    }

    private int checkSum_ ;
    /**
     * <pre>
     * 扩展校验字段
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @return The checkSum.
     */
    @java.lang.Override
    public int getCheckSum() {
      return checkSum_;
    }
    /**
     * <pre>
     * 扩展校验字段
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @param value The checkSum to set.
     * @return This builder for chaining.
     */
    public Builder setCheckSum(int value) {
      
      checkSum_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 扩展校验字段
     * </pre>
     *
     * <code>fixed32 check_sum = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckSum() {
      
      checkSum_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.gm.link.common.domain.protobuf.ProtoAck)
  }

  // @@protoc_insertion_point(class_scope:com.gm.link.common.domain.protobuf.ProtoAck)
  private static final com.gm.link.common.domain.protobuf.ProtoAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gm.link.common.domain.protobuf.ProtoAck();
  }

  public static com.gm.link.common.domain.protobuf.ProtoAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProtoAck>
      PARSER = new com.google.protobuf.AbstractParser<ProtoAck>() {
    @java.lang.Override
    public ProtoAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProtoAck(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProtoAck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProtoAck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gm.link.common.domain.protobuf.ProtoAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

