// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessage.proto

package com.gm.link.common.domain.protobuf;

public final class ProtoMessageOuter {
  private ProtoMessageOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ProtoMessage.proto\022\"com.gm.link.common" +
      ".domain.protobuf\"\317\003\n\014ProtoMessage\022\r\n\005mag" +
      "ic\030\001 \001(\007\022\017\n\007version\030\002 \001(\005\022\013\n\003cmd\030\003 \001(\005\022\023" +
      "\n\013msg_feature\030\004 \001(\005\022\016\n\006msg_id\030\005 \001(\t\022\016\n\006s" +
      "eq_id\030\006 \001(\t\022\021\n\ttimestamp\030\007 \001(\003\022\024\n\014from_u" +
      "ser_id\030\010 \001(\t\022\024\n\nto_user_id\030\t \001(\tH\000\022\025\n\013to" +
      "_group_id\030\n \001(\tH\000\022A\n\010msg_type\030\013 \001(\0162/.co" +
      "m.gm.link.common.domain.protobuf.Message" +
      "Type\022E\n\nmsg_status\030\014 \001(\01621.com.gm.link.c" +
      "ommon.domain.protobuf.MessageStatus\022\r\n\005f" +
      "lags\030\r \001(\005\022\030\n\013retry_count\030\016 \001(\005H\001\210\001\001\022\023\n\013" +
      "data_length\030\017 \001(\007\022\021\n\tcheck_sum\030\020 \001(\007\022\014\n\004" +
      "body\030\021 \001(\014B\016\n\014to_target_idB\016\n\014_retry_cou" +
      "nt*t\n\013MessageType\022\017\n\013MSG_UNKNOWN\020\000\022\014\n\010MS" +
      "G_TEXT\020\001\022\r\n\tMSG_IMAGE\020\002\022\r\n\tMSG_VOICE\020\003\022\r" +
      "\n\tMSG_VIDEO\020\004\022\014\n\010MSG_FILE\020\005\022\013\n\007MSG_CMD\020\006" +
      "*[\n\rMessageStatus\022\022\n\016STATUS_SENDING\020\000\022\017\n" +
      "\013STATUS_SENT\020\001\022\024\n\020STATUS_DELIVERED\020\002\022\017\n\013" +
      "STATUS_READ\020\003B9\n\"com.gm.link.common.doma" +
      "in.protobufB\021ProtoMessageOuterP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gm_link_common_domain_protobuf_ProtoMessage_descriptor,
        new java.lang.String[] { "Magic", "Version", "Cmd", "MsgFeature", "MsgId", "SeqId", "Timestamp", "FromUserId", "ToUserId", "ToGroupId", "MsgType", "MsgStatus", "Flags", "RetryCount", "DataLength", "CheckSum", "Body", "ToTargetId", "RetryCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
