// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoHB.proto

package com.gm.link.common.domain.protobuf;

public interface ProtoHBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gm.link.common.domain.protobuf.ProtoHB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 4字节魔数(0xDEADBEEF)
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  int getMagic();

  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * 固定为0x0003
   * </pre>
   *
   * <code>uint32 cmd = 3;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <pre>
   * 发送端机器标识
   * </pre>
   *
   * <code>string from_machine_id = 4;</code>
   * @return The fromMachineId.
   */
  java.lang.String getFromMachineId();
  /**
   * <pre>
   * 发送端机器标识
   * </pre>
   *
   * <code>string from_machine_id = 4;</code>
   * @return The bytes for fromMachineId.
   */
  com.google.protobuf.ByteString
      getFromMachineIdBytes();

  /**
   * <pre>
   * 接收端机器标识
   * </pre>
   *
   * <code>string to_machine_id = 5;</code>
   * @return The toMachineId.
   */
  java.lang.String getToMachineId();
  /**
   * <pre>
   * 接收端机器标识
   * </pre>
   *
   * <code>string to_machine_id = 5;</code>
   * @return The bytes for toMachineId.
   */
  com.google.protobuf.ByteString
      getToMachineIdBytes();

  /**
   * <pre>
   * 心跳扩展信息
   * </pre>
   *
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <pre>
   * 校验码(时间戳+机器ID)
   * </pre>
   *
   * <code>fixed32 check_sum = 7;</code>
   * @return The checkSum.
   */
  int getCheckSum();
}
