// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoAck.proto

package com.gm.link.common.domain.protobuf;

public interface ProtoAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gm.link.common.domain.protobuf.ProtoAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 4字节魔数(必须与请求一致)
   * </pre>
   *
   * <code>fixed32 magic = 1;</code>
   * @return The magic.
   */
  int getMagic();

  /**
   * <pre>
   * 协议版本
   * </pre>
   *
   * <code>uint32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * 固定为0x0002
   * </pre>
   *
   * <code>uint32 cmd = 3;</code>
   * @return The cmd.
   */
  int getCmd();

  /**
   * <pre>
   * 需要确认的原消息ID
   * </pre>
   *
   * <code>string original_msg_id = 4;</code>
   * @return The originalMsgId.
   */
  java.lang.String getOriginalMsgId();
  /**
   * <pre>
   * 需要确认的原消息ID
   * </pre>
   *
   * <code>string original_msg_id = 4;</code>
   * @return The bytes for originalMsgId.
   */
  com.google.protobuf.ByteString
      getOriginalMsgIdBytes();

  /**
   * <pre>
   * 2字节状态码，0-成功，其他-错误码
   * </pre>
   *
   * <code>uint32 status = 5;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return Whether the errorMsg field is set.
   */
  boolean hasErrorMsg();
  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <pre>
   * [可选]错误描述
   * </pre>
   *
   * <code>optional string error_msg = 6;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();

  /**
   * <pre>
   * 扩展校验字段
   * </pre>
   *
   * <code>fixed32 check_sum = 7;</code>
   * @return The checkSum.
   */
  int getCheckSum();
}
